[package]
name = "renderer-test-suite"
version = "0.1.0"
authors = ["Chinedu Francis Nwafili <frankie.nwafili@gmail.com>"]
edition = "2018"
publish = []

[dependencies]
base64 = "0.12"
conformer = {path = "../../"}
png = "0.16"